# Setup Travis CI pants configuration.
env:
  global:
    - JAVA_HOME="$HOME/opt/jdk1.8.0_131"
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'travis.pants.ini']"

# Copied from https://github.com/pantsbuild/pants/blob/master/.travis.yml.
before_cache:
  - sudo chown -R travis:travis "${HOME}" "${TRAVIS_BUILD_DIR}"
  - find build-support -name "*.py[co]" -delete
  - find ${HOME}/.ivy2/pants -type f -name "ivydata-*.properties" -delete
  - rm -f ${HOME}/.ivy2/pants/*.{css,properties,xml,xsl}
  - rm -rf ${HOME}/.ivy2/pants/com.example
  - rm -rf ${HOME}/.cache/pants/stats
  
cache:
  directories:
    - ${HOME}/.cache/pants
    - ${HOME}/.ivy2/pants
    - build-support/isort.venv
    - build-support/pants_dev_deps.venv

# Compile and run all unit tests.
language: python
python:
  - '2.7'

# Install JDK 1.8 copied from https://github.com/foursquare/fsqio/blob/master/.travis.yml.
before_script: |
  if ! ${HOME}/opt/jdk1.8.0_131/bin/java -version; then
    mkdir -p ~/opt
     wget --no-cookies --no-check-certificate --header \
       "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
       "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz"
    tar xzf jdk-8u131-linux-x64.tar.gz -C ~/opt
  fi
  
script: |
  java -version
  ./pants compile ::
  ./pants test ::
