env:
  global:
    # Use the Travis Configuration for Pants.
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'travis.pants.ini']"

language: python
python:
  - '2.7'

script: |
  ./pants fmt ::
  ./pants compile ::
  ./pants test ::
